### ISSUE TITLE
Include Easter Holidays 4/18 & 4/19 in Sales Rep Dashboard

### ISSUE THREAD

**Issue by KellenBM** [pbrink231/crm-issues#20]
**Is your feature request related to a problem? Please describe.**
Yes, sales reps will think their project is late, but really the artists are all on vacation

**Describe the solution you'd like**
include 4/18 and 4/19 like they are weekend days

**Describe alternatives you've considered**
just telling the reps

**Additional context**
  none

**Comment by pbrink231** [comment]
Updated to include Easter and weekends

**Comment by pbrink231** [comment]
https://github.com/pbrink231/crm-web/commit/2f8c690fb39a2ce92bb1cea753ee9f5b83d07fcc
