### ISSUE TITLE
roster name matching with packing list

### ISSUE THREAD

**Issue by maloneyjono** [pbrink231/crm-issues#34]
It seems that we are not matching the roster garment with the pack list. So if there is an indiv order with rostering this will happen in packing: 
Example: 
Jimmy - 1 JLMUN100 - Size M

Bag delivered: 
Ship to: Jimmy
Content: 
1 - JLMUN100 - size M
ROSTER NAME - COULD BE ANYONE!!! We are shipping the wrong pieces to the wrong people. Jimmy gets Dave's Uni.

**Comment by pbrink231** [comment]
#64 This issue created to fix this scenario
#66 This will help with the roster side.
