### ISSUE TITLE
CRM PO NOTE

### ISSUE THREAD

**Issue by maloneyjono** [pbrink231/crm-issues#38]
Please add the "CRM PO Note" text field to all areas where the PO table is in the CRM. 
You already have the CRM Po Note as a column in the production report, but we have no where to actually add/edit the note. 

The note field is really needed. Looking back at multiple POs on one deal we have no idea which PO is what...

**Comment by maloneyjono** [comment]
please do this.

**Comment by pbrink231** [comment]
in CRM
