### ISSUE TITLE
Send Shipping addresses to Poly via CSV order

### ISSUE THREAD

**Issue by maloneyjono** [pbrink231/crm-issues#43]
Ship to addresses have not been coming across to Poly. Need to mae sure CSV is syncing addresses to poly

**Comment by pbrink231** [comment]
addresses should be going now.

Working on fixing fedex to have
- Contact (first and last name)
- Company (not used by us.  Attn will change to this)
- Attn (used now but want to move to Company.  still possible from poly though)

**Comment by pbrink231** [comment]
converted Attn to Company

Removed full_name field and made a programmed field if needed.

https://github.com/pbrink231/crm-server/commit/e5cd44a7f10cf738deedeaefac0a2fec4ddabb30

**Comment by pbrink231** [comment]
in CRM
