### ISSUE TITLE
Fedex - Shipping report - push us alerts of transit/delivery issues

### ISSUE THREAD

**Issue by maloneyjono** [pbrink231/crm-issues#47]
We need to push shipping alert issues to our team. 
Example: 
1. customs delay or missing paperwork
2. Cant deliver 
etc
We need to have these issues highlighted in the shipping report for easy sorting and also get an alert on CRM.

**Comment by maloneyjono** [comment]
I heard that maybe Athlos already has this? Diego wrote some script to make this work? If so lets just use that??

**Comment by pbrink231** [comment]
I believe this is doneish

- Diego has set up so Fedex will send alerts to the email that is sent over.

@soul900 Please do not use my email if there is no email.

**Comment by soul900** [comment]
Done, i dont use your email.
