### ISSUE TITLE
Pricing in Poly - sync wit styles and send correct pricing with each CSV

### ISSUE THREAD

**Issue by maloneyjono** [pbrink231/crm-issues#50]

**Comment by pbrink231** [comment]
prices that are bad will have $1 or null.
Any bad prices will still go as 100000.  Will have carolina point out when this happens and will update poly correctly which will update future csv files.

**Comment by pbrink231** [comment]
this also relies on #27 to auto sync styles on a daily or hourly basis.

**Comment by pbrink231** [comment]
https://github.com/pbrink231/crm-web/commit/5a5bb9a7685797b4a09894b7a76de8699fc650c1

https://github.com/pbrink231/crm-server/commit/6a37aea300281220de80a77ede2099a94acf5966

**Comment by pbrink231** [comment]
in CRM
