### ISSUE TITLE
Dashboard - Widget Data pull

### ISSUE THREAD

**Issue by aliabrams** [pbrink231/crm-issues#53]
**Is your feature request related to a problem? Please describe.**
Have the data shown in the widgets (current art jobs, completed art jobs, open team stores, closed team stores) to reflect back to the past 6 weeks instead of 2 weeks.

**Comment by pbrink231** [comment]
changed to 42 days (6 weeks) on https://github.com/pbrink231/crm-server/commit/81a8e000bfda81516ff4f8c5a63e860199a3c624 commit.  Waiting for push

**Comment by pbrink231** [comment]
in CRM
